WIDTH = 1600
HEIGHT = 900
FPS = 60


PLAYER_SPEED = 300
PLAYER_SIZE = (124, 125)
PLAYER_MAX_HP = 150
PLAYER_COLLISION_HEIGHT_RATIO = 0.5
PLAYER_ATTACK_DAMAGE = 20
PLAYER_ATTACK_RANGE = 120
PLAYER_ATTACK_WIDTH = 100
PLAYER_ATTACK_COOLDOWN = 0.45
ATTACK_SLASH_RANGE_MULTIPLIER = 1.45
ATTACK_SLASH_WIDTH_MULTIPLIER = 1.25
ATTACK_WAVE_DAMAGE_MULTIPLIER = 0.65
ATTACK_WAVE_SPEED = 520
ATTACK_WAVE_RANGE = 360
ATTACK_WAVE_WIDTH = 58
ATTACK_WAVE_HEIGHT = 132
ATTACK_DOUBLE_HIT_DELAY = 0.18
ATTACK_DOUBLE_HIT_DAMAGE_MULTIPLIER = 0.75


XP_ORB_VALUE = 5
BASE_REQUIRED_XP = 20
XP_PER_LEVEL = 10
HP_PER_LEVEL = 5
DAMAGE_PER_LEVEL = 1

XP_ORB_RADIUS = 10
XP_ORB_COLOR = (90, 210, 255)
XP_ORB_GLOW_COLOR = (35, 110, 180)
XP_ORB_PICKUP_RADIUS = 18
STAR_DROP_CHANCE = 0.2
STAR_ORB_VALUE = 1
STAR_ORB_SIZE = 34
STAR_ORB_PICKUP_RADIUS = 22
STAR_ORB_GLOW_COLOR = (255, 206, 79)
STAR_ORB_IMAGE_PATH = "assets/images/skill_tree/star_for_tree.png"
FINAL_STAR_IMAGE_PATH = "assets/images/cave/final_star.png"
FINAL_STAR_SIZE = 72

HP_BAR_IMAGE_PATH = "assets/stats/hp.png"
HP_BAR_WIDTH = 405
HP_BAR_HEIGHT = 68

XP_BAR_IMAGE_PATH = "assets/stats/xp.png"
XP_BAR_WIDTH = 405
XP_BAR_HEIGHT = 69
XP_BAR_LERP_SPEED = 8.0


OBSTACLE_MIN_COUNT = 5
OBSTACLE_MAX_COUNT = 8
OBSTACLE_MIN_DISTANCE_FROM_PLAYER = 150
OBSTACLE_MIN_DISTANCE_FROM_EXIT = 100
OBSTACLE_MIN_DISTANCE_BETWEEN = 260
OBSTACLE_COLLISION_HEIGHT_RATIO = 0.35


OBSTACLE_TYPES = [

    ("stone", 25, (120, 80), True, 0, 0),
    ("bush", 25, (100, 100), False, 0, 0),
    ("timber", 20, (140, 60), True, 0, 0),
    ("tree", 20, (100, 120), True, 0, 0),
    ("crystal", 10, (80, 100), False, 10, 0.5),
]

OBSTACLE_VARIANT_COUNTS = {
    "stone": 3,
    "bush": 2,
    "timber": 2,
    "tree": 2,
    "crystal": 3,
}


STAGE_PLAY_AREA_MARGIN = 100
EXIT_ZONE_SIZE = (150, 150)


FADE_SPEED = 2.0
FADE_COLOR = (0, 0, 0)
ARENA_COUNT = 6
STAGE_TITLE_FONT_PATH = "assets/fonts/DigitalSemi-SerifPixel-Regular.otf"
STAGE_TITLE_FONT_SIZE = 54
STAGE_TITLE_SUBTITLE_FONT_SIZE = 30
STAGE_TITLE_FADE_TIME = 0.65
STAGE_TITLE_HOLD_TIME = 1.1
STAGE_TITLE_COLOR = (245, 238, 210)
STAGE_TITLE_SHADOW_COLOR = (18, 14, 10)
STAGE_CLEAR_MESSAGE_FONT_SIZE = 58
STAGE_CLEAR_MESSAGE_FADE_TIME = 0.7
STAGE_CLEAR_MESSAGE_HOLD_TIME = 2.2
STAGE_CLEAR_MESSAGE_COLOR = (245, 238, 210)
STAGE_CLEAR_MESSAGE_SHADOW_COLOR = (18, 14, 10)


COLOR_FOREST_NORMAL = (34, 139, 34)
COLOR_FOREST_INFECTED = (139, 69, 19)
COLOR_FOREST_BOSS = (50, 20, 50)
COLOR_CAVE = (35, 31, 48)

BOSS_EXIT_IMAGE_PATH = "assets/images/forest/boss/boss_over.png"
BOSS_EXIT_SIZE = (190, 125)
BOSS_STAR_REWARD = 10

DAMAGE_NUMBER_FONT_SIZE = 28
DAMAGE_NUMBER_DURATION = 0.75
DAMAGE_NUMBER_RISE_SPEED = 55
DAMAGE_NUMBER_PLAYER_HIT_COLOR = (255, 75, 75)
DAMAGE_NUMBER_ENEMY_HIT_COLOR = (90, 210, 255)


DAMAGE_COOLDOWN_DEFAULT = 0.5


ENEMY_SIZE = (128, 140)
ENEMY_MAX_HP = 40
ENEMY_DAMAGE = 10
ENEMY_SPEED = 140
ENEMY_ATTACK_COOLDOWN = 0.8
ENEMY_COLLISION_WIDTH_RATIO = 0.65
ENEMY_COLLISION_HEIGHT_RATIO = 0.55
ENEMY_PATH_UPDATE_TIME = 0.45
ENEMY_MAX_COUNT = 12
ENEMY_WAVE_SIZE = 4
ENEMY_WAVE_COUNT = 3
ENEMY_NEXT_WAVE_THRESHOLD = 0.7
ENEMY_SPAWN_PADDING = 16
ENEMY_MIN_DISTANCE_FROM_PLAYER_SPAWN = 420
DIFFICULTY_PER_ARENA = 0.15
ENEMY_HP_SCALE = 1.0
ENEMY_DAMAGE_SCALE = 1.0
ENEMY_SPEED_SCALE = 0.05
ENEMY_COUNT_PER_ARENA = 0.5

SLIME_PROJECTILE_DAMAGE = 12
SLIME_PROJECTILE_SPEED = 310
SLIME_PROJECTILE_SIZE = 28
SLIME_ATTACK_RANGE = 560
SLIME_ATTACK_COOLDOWN = 1.8
SLIME_PREFERRED_DISTANCE = 330

# Cave boss on the sixth (third cave) stage
CAVE_SLIME_BOSS_SIZE = (300, 280)
CAVE_SLIME_BOSS_MIN_SIZE = (150, 140)
CAVE_SLIME_BOSS_MAX_HP = 650
CAVE_SLIME_BOSS_FIRST_ATTACK_DELAY = 2.0
CAVE_SLIME_BOSS_ATTACK_INTERVAL = 3.2
CAVE_SLIME_BOSS_ATTACK_COUNT = 5
CAVE_SLIME_BOSS_MINIONS_PER_ATTACK = 5
CAVE_SLIME_BOSS_SHRINK_FACTOR = 0.87
CAVE_SLIME_MINION_SIZE = (82, 88)
CAVE_SLIME_STAR_PICKUP_RADIUS = 85

# Forest boss on the third and final stage
BOSS_SIZE = (220, 240)
BOSS_MAX_HP = 500
BOSS_APPEARANCE_FRAME_TIME = 0.35
BOSS_FIRST_ATTACK_DELAY = 2.1
BOSS_ATTACK_INTERVAL = 2.4
BOSS_ATTACK_ANIMATION_DURATION = 0.42
BOSS_SPIKE_DAMAGE = 24
BOSS_ORB_DAMAGE = 16
BOSS_ORB_SPEED = 250
BOSS_ORB_SIZE = 36
BOSS_ORB_COUNT = 7
BOSS_SPIKE_COUNT = 5
BOSS_STAGE_OBSTACLE_MIN_COUNT = 1
BOSS_STAGE_OBSTACLE_MAX_COUNT = 3


EXIT_LOCK_MESSAGE_TIME = 1.5

SKILL_LOCKED = "locked"
